name: Lint
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
