name: Test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu
          - windows
          - macOS
        go-version:
          - 1.23
          - 1.24
    name: 'Setup ${{ matrix.go-version }} on ${{ matrix.platform }}'
    runs-on: ${{ matrix.platform }}-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -json ./test/... | tee TestResults-${{ matrix.go-version }}-${{ matrix.platform }}.json

      - name: Generate test reports
        if: always()
        run: |
          go install github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@latest
          cat TestResults-${{ matrix.go-version }}-${{ matrix.platform }}.json | go-ctrf-json-reporter -output ctrf-${{ matrix.go-version }}-${{ matrix.platform }}.json

      - name: Publish Test Summary Results
        if: always()
        run: npx github-actions-ctrf ctrf-${{ matrix.go-version }}-${{ matrix.platform }}.json

      - name: Upload Go test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.go-version }}-${{ matrix.platform }}
          path: TestResults-${{ matrix.go-version }}-${{ matrix.platform }}.json
